services:
  - type: web
    name: novacoin-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        value: 8473264948:AAHOktEr2icFaGOF5x3hVogSYcC8sU-ec_8
      - key: SUPABASE_URL
        value: https://zjvnnzjrauxkmpdolsri.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqdm5uempyYXV4a21wZG9sc3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4Njg3MjcsImV4cCI6MjA4NzQ0NDcyN30.v3eezQVpGXLgzvhCHNDHOKzMdZVY4T9ixWPKqUdCVSA
      - key: APP_URL
        value: begkan.github.io/novascoin
      - key: PORT
        value: 3000
